config/routes.rb
Epets::Application.routes.draw do
  match '/' => 'static_pages#home', :as => :home
  match 'accessibility' => 'static_pages#accessibility', :as => 'accessibility'
  match 'how-it-works' => 'static_pages#how_it_works', :as => 'how_it_works'
  match 'terms-and-conditions' => 'static_pages#terms_and_conditions', :as => 'terms_and_conditions'
  match 'privacy-policy' => 'static_pages#privacy_policy', :as => 'privacy_policy'
  match 'crown-copyright' => 'static_pages#crown_copyright', :as => 'crown_copyright'
  match 'faq' => 'static_pages#faq', :as => 'faq'

  get 'feedback' => 'feedback#index', :as => 'feedback'
  get 'feedback/thanks' => 'feedback#thanks', :as => 'thanks_feedback'
  post 'feedback' => 'feedback#create', :as => 'feedback'

  resources :departments, :only => [:index, :show] do
    get 'info', :action => :info, :on => :collection, :as => :info
  end

  resources :petitions, :only => [:new, :show, :index] do
    collection do
      get 'check'
      get 'check_results'
    end

    member do
      post 'resend_confirmation_email'
      get  'thank-you', :action => :thank_you, :as => :thank_you
    end

    resource :signature, :only => [:new] do
      post 'new' => 'signatures#create', :as => :sign
      get 'thank-you', :action => :thank_you, :on => :collection, :as => :thank_you
      get 'signed', :action => :signed, :on => :collection, :as => :signed
    end
  end

  post 'petitions/new' => 'petitions#create', :as => :create_petition

  get 'search' => 'search#search', :as => :search

  resources :signatures, :only => [] do
    get 'verify/:token', :action => :verify, :on => :member, :as => :verify
  end

  namespace :admin do
    root :to => 'todolist#index'

    resource :search, :only => [:new] do
      get :result, :on => :member
      get :petition_by_id, :on => :member
    end

    resources :admin_users
    resources :petitions, :only => [:show, :edit, :update, :index] do
      collection do
        get :threshold
      end
      member do
        get :edit_response
        put :update_response
        get :edit_internal_response
        put :update_internal_response
        put :take_down
      end
    end
    resources :profile, :only => [:edit, :update]
    resources :reports,  :only => [:index]
    resources :user_sessions, :only => [:create]
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'login' => 'user_sessions#new', :as => :login
  end

  namespace :api do
    resources :petitions, :only => [:index, :show]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  caches_page :accessibility, :how_it_works, :terms_and_conditions, :privacy_policy, :crown_copyright, :faq
  caches_action :home, :expires_in => 5.minutes

  def home
    all_trending_petitions = TrendingPetition.order("signatures_in_last_hour desc").limit(12)
    @trending_petitions   = all_trending_petitions[0..5]
    @additional_petitions = all_trending_petitions[6..11]
  end

end

app/views/static_pages/accessibility.html.erb
<% content_for(:page_title) { "Accessibility - e-petitions" } %>
<div class="title_block">
  <h1>Accessibility</h1>
</div>

<div class="generic_text_block">
  <h2 class="top">Commitment to accessibility</h2>
  <p>
    We are committed to ensuring that the e-petitions website is usable and accessible to the widest possible audience, regardless of disability, capability or technology.
  </p>
  <p>
    We have maximised compatibility with current user agents, including assistive technologies, and will aim to be compatible with any future enhancements in assistive technology.
  </p>

  <h2>What did we do?</h2>
  <ul>
    <li>Our image content has a text equivalent that can be rendered by assistive technologies.</li>
    <li>We have provided text alternatives for any non-text content so that it can be changed into other forms people need such as large print, Braille, speech, symbols or simpler language.</li>
    <li>The navigation is clear, consistent and logical. </li>
    <li>All aspects of the navigation can be accessed using keyboard-only control and screen readers. </li>
    <li>An accessible search facility is provided. </li>
    <li>All links that can be selected via keyboard tabbing are visible or become visible when they receive focus. </li>
    <li>The tab order of the page is in a logical sequence that allows the user to be able to predict the next link to receive focus.</li>
    <li>The purpose of a link can be determined from the link text alone. </li>
    <li>Image links and buttons have an alt text that describes their purpose. </li>
    <li>Links that open in a new window can be identified by screen reader users from within the ‘links list’ dialogue of the screen reader. </li>
    <li>Where errors occur on a form, the user is informed as to which fields need attention and why. </li>
    <li>Our page titles help identify the general purpose and content of the page to the screen reader.</li>
    <li>Our online content complies with levels A and AA of the <%= new_window_link_to 'Web Content Accessibility Guidelines 2.0.', 'http://www.w3.org/TR/WCAG20/', :class => 'text_link_plain' %></li>
  </ul>

  <h2>Browsers</h2>
  <p>
    We have taken all reasonable steps to ensure that this website is as accessible as possible across the most common operating systems, internet-enabled hardware and web browsers currently available on the market.
  </p>
  <h3>Upgrading browsers</h3>
  <p>We would recommend upgrading your browser as far as your computer allows.  Later versions of browsers often have higher levels of security and better functions.</p>
  <p>Most browser suppliers will allow you to upgrade for free. Visit the browser's website to find out about the latest versions and to download them.  Browser downloads are very large; many browsers are also available on CDs such as those distributed by computer magazines.</p>

  <h2>Text resizing</h2>
  <p class="list_head">
    To resize the text on our pages you can follow these instructions:
  </p>
  <ul>
    <li>PC/Internet Explorer 6 - from the top menu bar, select ‘view’ and point to ‘text size’  </li>
    <li>PC/Internet Explorer 7 - from the menu bar underneath the search field, select ‘page’ and point to ‘text size’ </li>
    <li>PC/other browsers - to increase text size, hold down the CTRL key and press ‘+’ </li>
    <li>PC/other browsers - to reduce text size, hold down the CTRL key and press ‘-’ </li>
    <li>Mac/all browsers - to increase text size, hold down the Command key and press ‘+’ </li>
    <li>Mac/all browsers - to reduce text size, hold down the Command key and press ‘-’ </li>
  </ul>

  <h2>CAPTCHA</h2>

  <p>To prevent attacks by spamming, this site uses a CAPTCHA service when a user creates or signs an <span class="nowrap">e-petition</span>.</p>

  <p><%= new_window_link_to 'Find out more information about the CAPTCHA service', 'http://captchas.net', :class => 'text_link_plain' %></p>

</div>

app/views/static_pages/crown_copyright.html.erb
<% content_for(:page_title) { "Crown copyright - e-petitions" } %>
<div class="title_block">
  <h1>&copy; Crown copyright</h1>
</div>

<div class="generic_text_block">
  <p>The material on this website is subject to Crown copyright protection unless otherwise indicated.</p>
  
  <h2>Re-using Crown copyright material</h2>
  
  <p>You may re-use the text information on this website provided you identify the source and state that it is Crown copyright.</p>
  
  <p class="list_head">You may re-use the information on this website free of charge in any format, but you must:</p>
  <ul>
    <li>re-use the information accurately</li>
    <li>acknowledge the source of the information</li>
    <li>not re-use the information in a deliberately misleading way</li>
    <li>not re-use the information for promotion or advertising purposes except for promoting an e-petition</li>
    <li>not imply endorsement by <span class="nowrap">e-petitions</span>, another government department or other public sector organisation</li>
    <li>not mimic the style and appearance of the original information, for example by replicating the look of the e-petitions site</li>
  </ul>
  
  <h2>Images and photography</h2>
  
  <p>Images and photographs on this site are subject to Crown copyright protection unless otherwise indicated. You may re-use Crown copyright images subject to the conditions listed above.</p>
  
  <h2>Linking to <span class="nowrap">e-petitions</span> pages</h2>
  
  <p>You can link to <span class="nowrap">e-petitions</span> information pages. You don't have to ask permission to link to the website.</p>
  
  <h2>Re-using third party material</h2>
  
  <p>The permission to reproduce Crown protected material does not extend to any material on this site that is identified as being the copyright of a third party. Permission to use such material must be obtained from the copyright holder concerned.</p>
  
  <h2>Further information</h2>
  
  <p>For further information on Crown copyright policy and licensing arrangements, see the guidance featured on The National Archives website:</p>
  
  <%= new_window_link_to "Crown copyright - The National Archives website", "http://www.nationalarchives.gov.uk/information-management/our-services/crown-copyright.htm" %>
</div>

app/views/static_pages/faq.html.erb
<% content_for(:page_title) { "Frequently asked questions - e-petitions" } %>
<div class="title_block">
  <h1>Frequently asked questions</h1>
</div>

<div class="cut_in_block">
  <div class="wrapper">
    <p>A list of the more frequently asked questions is shown below. Select from the list of questions below for the answers.</p>
  </div>
</div>

<div class="faq_list_block generic_block">
  <ul class='faq'>
    <li>
      <%= link_to "Why haven't I received an email asking me to validate my email address?", '#question0', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to 'Why do I need to choose a government department when I create a new e-petition?', '#question1', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to 'What if more than one government department is responsible for my e-petition?', '#question2', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to "Why can't I change my e-petition or correct spelling errors?", '#question3', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to 'Is there a list of signatories for each e-petition?', '#question4', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to 'Why do you say my e-petition ‘could’ be debated in the House of Commons?', '#question5', :class => 'lightbox_link' %>
    </li>
	<li>
	  <%= link_to 'Can I merge my e-petition with another one?', '#question6', :class => 'lightbox_link' %>
	</li>
    <li>
      <%= link_to 'Can I delete my e-petition?', '#question7', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to 'Why hasn’t my signature been added to the total on the petition?', '#question8', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to 'Why can’t I vote against a petition?', '#question9', :class => 'lightbox_link' %>
    </li>
    <li>
      <%= link_to 'Can I send you a paper petition?', '#question10', :class => 'lightbox_link' %>
    </li>
  </ul>

  <%= link_to 'Return to home page', home_path, :class => "link_button large_link_button get_started_button" %>
</div>

<div class="generic_block faq_block">
  <div id="question0" class="faq_answer">
    <h2>Why haven't I received an email asking me to validate my email address?</h2>
    <p>You should check your spam or junk mail folder as the email may have ended up in there.  It is also possible during times when the e-petitions site is really busy that the email may take up to 4 hours to be sent. If you haven’t received your confirmation e-mail, you can ask for it to be resent using the link on the relevant petition page.</p>
  </div>
  <div id="question1" class="faq_answer">
    <h2>Why do I need to choose a government department when I create a new e-petition?</h2>
    <p>Each e-petition needs to be checked to make sure it complies with the terms and conditions of the service.  By choosing the government department responsible, your e-petition can be checked quickly by the most appropriate person.</p>

    <p>It also means the right department will see how many signatures your e-petition has and start the arrangements for a debate in the House of Commons, if appropriate.</p>
  </div>

  <div id="question2" class="faq_answer">
    <h2>What if more than one government department is responsible for my e-petition?</h2>
    <p>If the subject of your e-petition is covered by more than one department, choose the one you think is ‘most’ appropriate.  Don’t worry if you’re not certain; if the department you choose isn’t responsible, they will send it to the one that is.</p>
  </div>

  <div id="question3" class="faq_answer">
    <h2>Why can't I change my e-petition or correct spelling errors?</h2>
    <p>People sign your e-petition based on what it says at the time they sign. If you change the e-petition later, even to change small things such as spelling mistakes, the context may have changed and the people that have already signed it may no longer want their signature associated with the e-petition.</p>
  </div>

  <div id="question4" class="faq_answer">
    <h2>Is there a list of signatories for each e-petition?</h2>
    <p>We keep a record of who has signed each e-petition and show the total number of signatures. We also show the name of the person who created the e-petition, but we don’t show the names or other details of any of the signatories.</p>
  </div>

  <div id="question5" class="faq_answer">
    <h2>Why do you say my e-petition ‘could’ be debated in the House of Commons?</h2>
    <p>
    If your e-petition reaches the 100,000 signatures, it is eligible for a debate in the House of Commons. However a debate may not be possible:</p>
    <ul>
      <li>if the subject of the e-petition is currently going through legal proceedings, it may be inappropriate for a debate to be held;</li>
      <li>if there has just been, or is about to be, a debate in the House of Commons on the same topic as your e-petition.</li>
    </ul>
  </div>

  <div id="question6" class="faq_answer">
	<h2>Can I merge my e-petition with another one?</h2>
	<p>People sign your e-petition based on what it says at the time they sign. It wouldn’t be possible to merge similar e-petitions without people having their signature associated with a petition they may not have seen or agreed to, so we do not allow this.</p>
  </div>

  <div id="question7" class="faq_answer">
	<h2>Can I delete my e-petition?</h2>
	<p>If your e-petition has fewer than 100 signatures, we can remove it from the site. To do this, please contact us using the form on the  <%= link_to 'Feedback', feedback_path %> page.</p>
  </div>

  <div id="question8" class="faq_answer">
	<h2>Why hasn’t my signature been added to the total on the petition?</h2>
	<p>Once an e-petition has been signed, the updating of the number of signatures does not take place straight away. Instead, the signature total which appears on the site refreshes at regular intervals, rather than at the moment the signature is added.</p>
  </div>

  <div id="question9" class="faq_answer">
	<h2>Why can’t I vote against a petition?</h2>
	<p>The petitions system as it currently works allows individuals to raise issues which they feel are important for discussion, and does not mean that Parliament or Government will necessary agree with or support the issues raised; a combination of 'for' and 'against' signatures would still suggest that people would find an issue important and wish it to be discussed.</p>
  </div>

  <div id="question10" class="faq_answer">
	<h2>Can I send you a paper petition?</h2>
	<p>It is not possible to include a paper petition as part of reaching the threshold of 100 000 signatures to make a petition eligible for debate in the House of Commons.  This is because paper petitions do not allow the Government to verify signatures to the same degree as with e-petitions.</p>
    <p>The e-petitions system is not intended to replace the current paper based system of public petitions in the House of Commons. For more information about the paper based Parliamentary Petitions, you can visit the UK Parliament website. The Backbench Business Committee, who are responsible for the scheduling of any debates on e-petitions, have made clear that they will continue to consider paper petitions when choosing subjects for debates.</p>
  </div>
</div>

<%= content_for :js, javascript_include_tag('lightbox') %>

app/views/static_pages/home.html.erb
<div class="cta_block" id="search_pet_cta_block">
  <h1>e-petitions – create and sign petitions online</h1>

  <form method="get" action="/search">
    <label for="search">Search for an e-petition to sign</label>
    <input type='text' name="q" id="search" />
    <input type='submit' value='Search' class="button" id="home_search_button"/>
  </form>

  <%= link_to 'View all e-petitions', petitions_path, :class => 'large_link view_all_epetitions' %>
  <%= link_to 'View e-petitions by government department', departments_path, :class => 'large_link department_search' %>
</div>

<% if @trending_petitions.present? %>
  <div class="cta_block clearfix" id="trending_cta_block">
    <h1>Trending e-petitions</h1>
    <p class='explanatory_text'>
      Most active e-petitions in the last hour.
      Page last updated <%= last_updated_at_time Time.zone.now %>.
    </p>
    <ul>
      <% @trending_petitions.each do |trending_petition| %>
        <%= render 'petitions/trending_petition', :trending_petition => trending_petition %>
      <% end -%>
    </ul>

    <% if @additional_petitions.present? %>
      <%= link_to 'See more trending e-petitions', '#', :id => 'see_more_trending_petitions' %>

      <div id="additional_trending_petitions_block">
        <ul>
          <% @additional_petitions.each do |trending_petition| %>
            <%= render 'petitions/trending_petition', :trending_petition => trending_petition %>
          <% end -%>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

<div class="cta_block" id="create_pet_cta_block">
  <h2>What are e-petitions?</h2>
  <p>e-petitions <span class="nowrap">are</span> an easy, personal way for you to influence government and Parliament in the UK. You can create an e-petition about anything that the government is responsible for and if it gets at least 100,000 signatures, it will be considered for debate in the House of Commons.  You can find more information about how the House of Commons deals with e-petitions on the <%= new_window_link_to "Backbench Business Committee website", "http://www.parliament.uk/bbcom" %>.</p>
  <%= link_to 'How e-petitions work', how_it_works_path, :class => 'large_link' %>
  <%= link_to "Create a new e-petition", check_petitions_path, :class => 'link_button large_link_button' %>
</div>

<% content_for :js do %>
  <script type="text/javascript">
  //<![CDATA[
    $().ready(function(){
      $('#see_more_trending_petitions').show();
      $('#see_more_trending_petitions').click(function(){
        $(this).hide();
        $('#additional_trending_petitions_block').show();
        return false;
      });
    });
  //]]>
  </script>
<% end %>

app/views/static_pages/how_it_works.html.erb
<% content_for(:page_title) { "How e-petitions works - e-petitions" } %>
<div class="title_block">
  <h1>How e-petitions work</h1>
</div>

<div class="cut_in_block">
  <div class="wrapper">
    <p>Click the "<span class="info_link">info</span>" icon to find out more about each step.</p>
  </div>
</div>

<div class="how_it_works">
  <ul>
    <li class="text_1">
      Search existing <span class="nowrap">e-petitions</span> before creating a new one
      <%= link_to 'info', "#search", :class => 'info_link lightbox_link' %>
      <div class="connector"></div>
    </li>
    <li class="text_2">
      Create your <span class="nowrap">e-petition</span>
      <%= link_to 'info', "#start", :class => 'info_link lightbox_link' %>
      <div class="connector"></div>
    </li>
    <li class="text_3">
      It will be checked by a government department
      <%= link_to 'info', "#checked", :class => 'info_link lightbox_link' %>
      <div class="connector"></div>
    </li>
    <li class="text_4">
      An <span class="nowrap">e-petition</span><br/>can be open for up to 1 year
      <%= link_to 'info', "#duration", :class => 'info_link lightbox_link' %>
      <div class="connector"></div>
    </li>
    <li class="text_5">
      The public can sign it
      <%= link_to 'info', "#sign", :class => 'info_link lightbox_link' %>
      <div class="connector"></div>
    </li>
    <li class="text_6">
      <span class="pre_text">If you collect</span>
      <span class="text_replace">100,000</span>
      <span class="post_text">signatures, your <span class="nowrap">e-petition</span> could be debated in the House of Commons</span>
      <%= link_to 'info', "#commons", :class => 'info_link lightbox_link' %>
    </li>
  </ul>

  <%= link_to 'Return to home page', home_path, :class => "link_button large_link_button get_started_button" %>
</div>

<div class="generic_block  how_it_works_block">
  <div id="search" class="how_it_works_explanation">
    <h2>Search existing e-petitions before creating a new one</h2>
    <p>
      Before you create a new e-petition, search the site to make sure there isn’t one that covers your issue. If a new <span class="nowrap">e-petition</span> is the same as one that’s already on the site, it will be rejected.</p>
    <p>
      Search will look for every word you type. For example if you search for ‘the government’, you will see results for every <span class="nowrap">e-petition</span> that includes the words ‘the’ or ‘government’.</p>
    <p>Use key words that are specific to the issue to get more relevant results. For example ‘road tax’ will give better results than ‘government action on reducing road tax’.</p>
  </div>

  <div id="start" class="how_it_works_explanation">
    <h2>Create your <span class="nowrap">e-petition</span></h2>
    <p>
      Your e-petition must be a request for the government to do something.</p>
    <p>
      You need to choose which government department looks after your issue. For example road issues should be sent to the Department for Transport. There’s a list of government departments to help you choose.</p>
    <p>You will need to provide your name, address and email before you can submit your <span class="nowrap">e-petition</span>.</p>
    <p>Once you’ve submitted your <span class="nowrap">e-petition</span>, you will receive an email with a link to confirm your email address is correct. Your <span class="nowrap">e-petition</span> cannot be processed until you click on the link.</p>
  </div>

  <div id="checked" class="how_it_works_explanation">
    <h2>It will be checked by a government department</h2>
    <p>
      Your <span class="nowrap">e-petition</span> will be checked by the government department that looks after your issue. This is to make sure it complies with the <%= link_to 'Terms & Conditions', terms_and_conditions_path %> for creating an <span class="nowrap">e-petition</span>.</p>
    <p class="list">
      The main reasons why your <span class="nowrap">e-petition</span> could be rejected are</p>
    <ul>
      <li>there’s already an <span class="nowrap">e-petition</span> on the same issue</li>
      <li>it contains confidential, libellous, false or defamatory statements</li>
      <li>it contains offensive, joke or nonsense content</li>
      <li>the issue is not the responsibility of the government</li>
      <li>it’s about honours or appointments</li>
      <li>it does not include a request for action</li>
    </ul>
    <p>It can take up to 7 days to check your <span class="nowrap">e-petition</span>. You will receive an email that tells you if your <span class="nowrap">e-petition</span> has been accepted or not.</p>
  </div>

  <div id="duration" class="how_it_works_explanation">
    <h2>An <span class="nowrap">e-petition</span> can be open for up to 1 year</h2>
    <p>Usually an <span class="nowrap">e-petition</span> stays open for 12 months. You can choose if you want your <span class="nowrap">e-petition</span> to close sooner than this.</p>
    <p>If you set a shorter period, you still need to get 100,000 signatures for your issue to be eligible for debate in the House of Commons.</p>
    <p>At the end of the set period, the <span class="nowrap">e-petition</span> closes. No further signatures can be added to it.</p>
  </div>

  <div id="sign" class="how_it_works_explanation">
    <h2>The public can sign it</h2>
    <p>If your <span class="nowrap">e-petition</span> is published, you will be sent a link (URL) to your <span class="nowrap">e-petition</span> page. You can share this with anyone you want to sign your <span class="nowrap">e-petition</span>.</p>
    <p>Every <span class="nowrap">e-petition</span> page also has links so you can easily publish it on social networking sites.</p>
    <p class="list">
	  Anyone signing your <span class="nowrap">e-petition</span>:</p>
	<ul>
	  <li>will need to provide their name, address and email</li>
	  <li>can choose to receive email updates from the government about the <span class="nowrap">e-petition</span></li>
	</ul>
  </div>

  <div id="commons" class="how_it_works_explanation">
    <h2>If you collect 100,000 signatures, your <span class="nowrap">e-petition</span> is eligible to be debated in the House of Commons</h2>
    <p>The <span class="nowrap">e-petitions</span> House of Commons Backbench Business Committee receives notification from the Leader of the House once an e-petition has 100,000 signatures. The Backbench Business Committee meets weekly when the House of Commons is sitting to hear representations from MPs for debates in backbench time. The Committee can consider any subject for debate, including those raised in e-petitions or national campaigns but an MP must make the case for their consideration.</p>
    <p> More information can be found on the <%= new_window_link_to "Backbench Business Committee website", "http://www.parliament.uk/bbcom" %>. </p>
  </div>
</div>

<%= content_for :js, javascript_include_tag('lightbox') %>

app/views/static_pages/privacy_policy.html.erb
<% content_for(:page_title) { "Privacy policy - e-petitions" } %>
<div class="title_block">
  <h1>Privacy policy</h1>
</div>

<div class="generic_text_block">
  <h2>Personal data - creating an e-petition</h2>

  <p>If you create an e-petition on this website, you must provide us with your name, address and email so we can contact you about your e-petition. Your personal information will only be used for this purpose. </p>

  <p>Your name (but no other details) will be published on your e-petition.</p>

  <h2>Personal data - signing an e-petition</h2>
  <p>When you sign an e-petition on this website, you must provide us with your name, address and email so we can check that signatures are genuine. Your personal information will only be used for this purpose. </p>

  <p>Your personal details will not be published on the site and the person who created the e-petition can’t see them. </p>

  <p>We will only contact you about an e-petition if you ask to receive updates when you sign it.</p>

  <h2>Cookies</h2>
  
  <p>We use cookies to collect information about how visitors use our site. We use the information to compile reports and to help us improve the site. </p>

  <p class='list_head'>The cookies we use collect information anonymously. They let us:</p>
  <ul>
    <li>count the number of visitors to the site</li>
    <li>understand how visitors got to the site</li>
    <li>understand which pages are viewed</li>
  </ul>

  <p>Our web servers automatically log the IP/internet address of your computer to help prevent attacks on the e-petitions website.</p>

  <h2>Freedom of information</h2>
  
  <p>We already publish on this website the data we hold that you can request under the Freedom of Information Act.</p>

  <p>If you wish to see the personal data that we hold about you, send a <%= new_window_link_to "Subject Access Request", "http://www.ico.gov.uk/for_the_public/personal_information/how_manage/access_info.aspx" %> to <%= mail_to "foiteam@cabinet-office.x.gsi.gov.uk" %>. You must include the email address you used to create or sign an e-petition. Our response will be sent to this email address to protect your privacy. </p>

  <p>We reserve the right to charge a fee for providing your data.</p>
</div>