config/routes.rb
Epets::Application.routes.draw do
  match '/' => 'static_pages#home', :as => :home
  match 'accessibility' => 'static_pages#accessibility', :as => 'accessibility'
  match 'how-it-works' => 'static_pages#how_it_works', :as => 'how_it_works'
  match 'terms-and-conditions' => 'static_pages#terms_and_conditions', :as => 'terms_and_conditions'
  match 'privacy-policy' => 'static_pages#privacy_policy', :as => 'privacy_policy'
  match 'crown-copyright' => 'static_pages#crown_copyright', :as => 'crown_copyright'
  match 'faq' => 'static_pages#faq', :as => 'faq'

  get 'feedback' => 'feedback#index', :as => 'feedback'
  get 'feedback/thanks' => 'feedback#thanks', :as => 'thanks_feedback'
  post 'feedback' => 'feedback#create', :as => 'feedback'

  resources :departments, :only => [:index, :show] do
    get 'info', :action => :info, :on => :collection, :as => :info
  end

  resources :petitions, :only => [:new, :show, :index] do
    collection do
      get 'check'
      get 'check_results'
    end

    member do
      post 'resend_confirmation_email'
      get  'thank-you', :action => :thank_you, :as => :thank_you
    end

    resource :signature, :only => [:new] do
      post 'new' => 'signatures#create', :as => :sign
      get 'thank-you', :action => :thank_you, :on => :collection, :as => :thank_you
      get 'signed', :action => :signed, :on => :collection, :as => :signed
    end
  end

  post 'petitions/new' => 'petitions#create', :as => :create_petition

  get 'search' => 'search#search', :as => :search

  resources :signatures, :only => [] do
    get 'verify/:token', :action => :verify, :on => :member, :as => :verify
  end

  namespace :admin do
    root :to => 'todolist#index'

    resource :search, :only => [:new] do
      get :result, :on => :member
      get :petition_by_id, :on => :member
    end

    resources :admin_users
    resources :petitions, :only => [:show, :edit, :update, :index] do
      collection do
        get :threshold
      end
      member do
        get :edit_response
        put :update_response
        get :edit_internal_response
        put :update_internal_response
        put :take_down
      end
    end
    resources :profile, :only => [:edit, :update]
    resources :reports,  :only => [:index]
    resources :user_sessions, :only => [:create]
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'login' => 'user_sessions#new', :as => :login
  end

  namespace :api do
    resources :petitions, :only => [:index, :show]
  end
end

app/models/signature.rb
# == Schema Information
#
# Table name: signatures
#
#  id               :integer(4)      not null, primary key
#  name             :string(255)     not null
#  email            :string(255)     not null
#  state            :string(10)      default("pending"), not null
#  perishable_token :string(255)
#  postcode         :string(255)
#  country          :string(255)
#  ip_address       :string(20)
#  petition_id      :integer(4)
#  created_at       :datetime
#  updated_at       :datetime
#  notify_by_email  :boolean(1)      default(FALSE)
#  last_emailed_at  :datetime
#

class Signature < ActiveRecord::Base
  PENDING_STATE = 'pending'
  VALIDATED_STATE = 'validated'
  STATES = [PENDING_STATE, VALIDATED_STATE]

  attr_accessible :name, :email, :email_confirmation, :address, :town, :postcode, :country, :humanity, :uk_citizenship, :terms_and_conditions, :notify_by_email
  before_create :set_perishable_token

  # = Relationships =
  belongs_to :petition

  # = Validations =
  validates_format_of :email, :with => Authlogic::Regex.email, :unless => 'email.blank?', :message => "Email not recognised."
  validates_presence_of :email_confirmation, :on => :create, :message => "%{attribute} must be completed"
  validates_confirmation_of :email, :message => "Email should match confirmation", :on => :create

  validate do |signature|
    matcher = Signature.where(:email => signature.email, :petition_id => signature.petition_id)
    matcher = matcher.where("signatures.id != ?", signature.id) unless signature.new_record?
    existing_email_address_count = matcher.count
    break if existing_email_address_count == 0
    if existing_email_address_count > 1
      signature.errors.add(:email, 'This email address is not allowed to sign this petition again')
      break
    end
    existing_signature =  matcher.first
    if (existing_signature.name.strip.downcase == signature.name.strip.downcase)
      signature.errors.add(:email, 'You cannot sign this petition again')
      break
    end
    if (existing_signature.postcode.gsub(/\s+/,'').downcase !=
        signature.postcode.gsub(/\s+/,'').downcase)
      signature.errors.add(:email, 'This email address is not allowed to sign this petition again')
      break
    end

  end
  validates_presence_of :name, :email, :country, :message => "%{attribute} must be completed"
  validates_presence_of :postcode, :message => "%{attribute} must be completed", :if => "country == 'United Kingdom'"
  validates_inclusion_of :state, :in => STATES, :message => "'%{value}' not recognised"

  validates_acceptance_of :humanity, :accept => true, :message => "The captcha was not filled in correctly.", :if => :new_record?, :allow_nil => false
  validates_acceptance_of :uk_citizenship, :message => "You must be a British citizen or normally live in the UK to create or sign petitions.", :if => :new_record?, :allow_nil => false
  validates_acceptance_of :terms_and_conditions, :message => "You must accept the terms and conditions.", :if => :new_record?, :allow_nil => false
  validates_presence_of :address, :town, :if => :new_record?, :message => "%{attribute} must be completed"

  # = Finders =
  scope :validated, :conditions => ['state = ?', VALIDATED_STATE]
  scope :notify_by_email, :conditions => ['notify_by_email = ?', true]
  scope :need_emailing, lambda { |job_datetime|
    validated.notify_by_email.where('last_emailed_at is null or last_emailed_at < ?', job_datetime)
  }
  scope :for_email, lambda { |email| where(:email => email) }
  scope :in_days, lambda {|number_of_days| validated.where("updated_at > ?", number_of_days.day.ago) }

  # = Methods =
  attr_accessor :humanity
  attr_accessor :uk_citizenship
  attr_accessor :terms_and_conditions
  attr_accessor :address
  attr_accessor :town

  def creator?
    petition.creator_signature == self
  end

  def pending?
    state == PENDING_STATE
  end

  def validated?
    state == VALIDATED_STATE
  end

  def postal_district
    postcode.upcase.match(/[A-Z]{1,2}[0-9]{1,2}[A-Z]?/).to_s
  end

  private
  def set_perishable_token
    self.perishable_token = Authlogic::Random.friendly_token
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  before_filter :retrieve_petition, :only => [:new, :create, :thank_you, :signed]
  ssl_required :new, :create
  ssl_allowed :thank_you, :verify
  include ActionView::Helpers::NumberHelper

  respond_to :html

  def new
    @signature = Signature.new(:petition => @petition, :country => "United Kingdom")
  end

  def create
    params[:signature][:humanity] = Captcha.verify(params[:captcha_response_field], params[:captcha_string])

    @signature = Signature.new(params[:signature])
    @signature.email.strip!
    @signature.petition = @petition
    if (@signature.save)
      send_email_to_petition_signer(@signature)
    end
    respond_with @signature, :location => thank_you_petition_signature_path(@petition)
  end

  def verify
    @signature = Signature.find(params[:id])

    if @signature.perishable_token == params[:token]
      @signature.perishable_token = nil
      @signature.state = Signature::VALIDATED_STATE
      @signature.save(:validate => false)

      # if signature is that of the petition's creator, mark the petition as validated
      if @signature.petition.creator_signature == @signature
        @signature.petition.state = Petition::VALIDATED_STATE
        @signature.petition.save!

    # else signature is from an ordinary signee so let's redirect to petition's page
      else
        redirect_to signed_petition_signature_path(@signature.petition) and return
      end
    else
      # We've found the signature, but it's already been verified.
      if @signature.state == Signature::VALIDATED_STATE
        flash[:notice] = "Thank you. Your signature has already been added to the <span class='nowrap'>e-petition</span>.".html_safe
        redirect_to signed_petition_signature_path(@signature.petition) and return
      else
        raise ActiveRecord::RecordNotFound
      end
    end
  end

  private
  def retrieve_petition
    @petition = Petition.visible.find(params[:petition_id])
  end

  def send_email_to_petition_signer(signature)
    PetitionMailer.email_confirmation_for_signer(signature).deliver
  end
end

app/views/signatures/_form.html.erb
<%= form_row :for => [signature, :name] do %>
  <%= f.label :name %>
  <%= f.text_field :name, :tabindex => increment  %>
  <%= error_messages_for_field signature, :name %>
  <div class="tip">
    <div class="arrow"></div>
    <p>Give your full name, not the name of a company or organisation.</p>
  </div>

<% end %>

<%= form_row :for => [signature, :email] do %>
  <%= f.label :email %>
  <%= f.text_field :email, :type => 'email', :tabindex => increment %>
  <%= error_messages_for_field signature, :email %>
<% end %>

<%= form_row :for => [signature, :email_confirmation] do %>
  <%= f.label :email_confirmation %>
  <%= f.text_field :email_confirmation, :type => 'email', :tabindex => increment,
                   :onpaste => "return false", :autocomplete => 'off' %>
<% end %>

<%= form_row :class => 'is_uk_citizen_row', :for => [signature, :uk_citizenship] do %>
  <p class="label">British citizen or UK resident?</p>
  <ul class="radio_button_list">
    <li>
    <%= f.radio_button :uk_citizenship, 1, :title => "Yes, I am a British citizen or UK resident", :tabindex => increment %>
      <%= f.label :uk_citizenship_1, "yes" %>
    </li>
    <li>
    <%= f.radio_button :uk_citizenship, 0, :title => "No, I am not a British citizen or UK resident", :tabindex => increment %>
      <%= f.label :uk_citizenship_0, "no" %>
    </li>
  </ul>

  <%= error_messages_for_field signature, :uk_citizenship %>
<% end %>

<%= form_row :class => 'address_row', :for => [signature, :address] do %>
  <%= f.label :address %>
  <%= f.text_area :address, :class => 'address', :tabindex => increment %>
  <%= error_messages_for_field signature, :address %>
<% end %>

<%= form_row :for => [signature, :town] do %>
  <%= f.label :town %>
  <%= f.text_field :town, :tabindex => increment %>
  <%= error_messages_for_field signature, :town %>
<% end %>

<%= form_row :for => [signature, :postcode] do %>
  <%= f.label :postcode %>
  <%= f.text_field :postcode, :class => 'postcode', :tabindex => increment %>
  <%= error_messages_for_field signature, :postcode %>
<% end %>

<%= form_row :for => [signature, :country] do %>
  <%= f.label :country %>
  <%= f.select :country, countries_for_select, {}, :tabindex => increment %>
  <%= error_messages_for_field signature, :country %>
<% end %>

app/views/signatures/_notify_by_email.html.erb
<%= form_row :class => 'checkbox_row', :for => [signature, :notify_by_email] do %>
  <%= f.check_box :notify_by_email, :tabindex => increment  %>
  <%= f.label :notify_by_email, "Email me updates about this <span class='nowrap'>e-petition</span>".html_safe %>
  <%= error_messages_for_field signature, :notify_by_email %>
  (We will not share your email address with anyone or use it for any other purpose)
<% end %>

app/views/signatures/_terms_and_conditions.html.erb
<%= form_row :class => 'checkbox_row', :for => [signature, :terms_and_conditions] do %>
  <%= f.check_box :terms_and_conditions, :tabindex => increment %>
  <%= f.label :terms_and_conditions, 
              raw("I agree to the #{new_window_link_to('Terms & Conditions', 
                                                   terms_and_conditions_path, 
                                                   :tabindex => increment, 
                                                   :class => 'text_link_plain terms_and_conditions')}")
  %>
  <%= error_messages_for_field signature, :terms_and_conditions %>
<% end %>

app/views/signatures/new.html.erb
<%= link_to 'lightbox', "#make_sure_your_signature_counts", :class => 'lightbox_link', :id => 'make_sure_your_signature_counts_link' %>

<% content_for(:page_title) { "#{@petition.title} - Sign this e-petition - e-petitions" } %>
<% # set tab index to start at 5
 increment(5) %>
<div class="title_block">
  <h2>Sign this e-petition</h2>
  <h1 class="petition_title"><%= @petition.title %></h1>
</div>

<%= form_for @signature, :url => sign_petition_signature_path, :html => {:class => 'wizard_form new_petition_form'} do |f| %>
  <fieldset>
    <%= render :partial => 'signatures/form', :locals => { :f => f, :signature => @signature } %>

    <%= form_row :for => [@signature, :humanity], :class => 'captcha_row' do %>
      <%= render :partial => 'shared/captcha_widget', :locals => { :f => f, :signature => @signature } %>
    <% end -%>

    <%= render :partial => 'notify_by_email', :locals => { :f => f, :signature => @signature } %>
    <%= render :partial => 'terms_and_conditions', :locals => { :f => f, :signature => @signature } %>

    <div class="row button_row">

      <%= link_to "Back", petition_path(@petition), :class => "backwards_action link_button", :tabindex => increment(2) %>
      <%= f.submit "Sign this e-petition", :class => 'button', :tabindex => increment(-1) %>
      <% increment(2) -%>
    </div>
  </fieldset>
<% end -%>

<div class="generic_block faq_block">
<div id="make_sure_your_signature_counts" class="faq_answer">
  <h2>Make your signature count</h2>
  <p>
    You'll need a current email address to sign this e-petition.
  </p>

  <p>
    We'll send you an email with a link - your signature <strong>won't</strong> be added to the e-petition until you've clicked on that link.
  </p>
</div>
</div>


<%= content_for :js, javascript_include_tag('lightbox') %>
<% content_for :js do %>
<script type="text/javascript">
//<![CDATA[
$().ready(function() {

  <% # do not display popup if we have validation errors -%>
  <%- if @signature.errors.empty? -%>
  (function(){
    $('.lightbox .link_button').removeClass('cancel_action').text('Continue');
    $('#make_sure_your_signature_counts_link').click();
  })();
  <%- end -%>

  window.signature_form = new E_PETS.FormController($('#new_signature'));
  signature_form.validates('signature[name]', {
    method: E_PETS.FormController.validation_methods.validate_presence,
    message: "Name must be completed."
  });
  signature_form.validates('signature[email]', {
    method: E_PETS.FormController.validation_methods.validate_presence,
    message: "Email must be completed."
  });
  signature_form.validates('signature[email]', {
    method: [E_PETS.FormController.validation_methods.validate_format, E_PETS.FormController.validation_formats.email],
    message: "Email not recognised."
  });
  signature_form.validates('signature[email_confirmation]', {
    method: [E_PETS.FormController.validation_methods.validate_confirmation, 'signature[email]'],
    message: "Email must match confirmation."
  });
  signature_form.validates('signature[uk_citizenship]', {
    method: [E_PETS.FormController.validation_methods.validate_radio_group_value, '1'],
    message: "You must be a British citizen or normally live in the UK to create or sign e-petitions."
  });
  signature_form.validates('signature[address]', {
    method: E_PETS.FormController.validation_methods.validate_presence,
    message: "Address must be completed."
  });
  signature_form.validates('signature[town]', {
    method: E_PETS.FormController.validation_methods.validate_presence,
    message: "Town must be completed."
  });
  signature_form.validates('signature[postcode]', {
    method: E_PETS.FormController.validation_methods.validate_presence,
    message: "Postcode must be completed.",
    when: function() {
      return $("select[name*=country]").val() == "United Kingdom";
    }
  });
  signature_form.validates('signature[postcode]', {
    method: [E_PETS.FormController.validation_methods.validate_format, E_PETS.FormController.validation_formats.postcode],
    message: "Postcode not recognised.",
    when: function() {
      return $("select[name*=country]").val() == "United Kingdom";
    }
  });
  signature_form.validates('signature[terms_and_conditions]', {
    method: E_PETS.FormController.validation_methods.validate_checked,
    message: "You need to accept the terms and conditions."
  });
});
//]]>
</script>
<% end %>

app/views/signatures/signed.html.erb
<% content_for(:page_title) { "Thank you - e-petitions" } %>
<% content_for :title do %>
<div class="title_block">
  <h1>Thank you.</h1>
</div>
<% end %>

<div class="cta_block thank_you_block">
  <p>Your signature has now been added to this e-petition.</p>

  <%= link_to "Click here to view the e-petition", petition_path(@petition), :class => 'link_button large_link_button return_to_homepage_button' %>
</div>

app/views/signatures/thank_you.html.erb
<% content_for(:page_title) { "Thank you - e-petitions" } %>
<% content_for :title do %>
<div class="title_block">
  <h1>Nearly there, now check your email to finish</h1>
</div>
<% end %>

<div class="cta_block thank_you_block">
  <p>An email will be sent to you now to confirm your email address.  If we're busy this may take a few hours to arrive, thanks for your patience.</p>

  <p>We can't add your signature to the e-petition until you've clicked on the link in this email.</p>

  <%= link_to "Click here to view the e-petition", petition_path(@petition), :class => 'link_button large_link_button return_to_homepage_button' %>
</div>

app/views/signatures/verify.html.erb
<% content_for(:page_title) { "Thank you for verifying your email address - e-petitions" } %>
<% content_for :title do %>
<div class="title_block">
  <h1>Thank you.</h1>
</div>
<% end %>

<div class="cta_block thank_you_block">
  <p>You have now confirmed your email address.</p>

  <p>Your e-petition will now be checked to make sure it complies with the terms &amp; conditions for creating an e-petition.</p>

  <p>Checking can take up to 7 days, so we'll send you an email once this is done.</p>

  <%= link_to "Return to home page", home_path, :class => 'link_button large_link_button return_to_homepage_button' %>
</div>