config/routes.rb
Epets::Application.routes.draw do
  match '/' => 'static_pages#home', :as => :home
  match 'accessibility' => 'static_pages#accessibility', :as => 'accessibility'
  match 'how-it-works' => 'static_pages#how_it_works', :as => 'how_it_works'
  match 'terms-and-conditions' => 'static_pages#terms_and_conditions', :as => 'terms_and_conditions'
  match 'privacy-policy' => 'static_pages#privacy_policy', :as => 'privacy_policy'
  match 'crown-copyright' => 'static_pages#crown_copyright', :as => 'crown_copyright'
  match 'faq' => 'static_pages#faq', :as => 'faq'

  get 'feedback' => 'feedback#index', :as => 'feedback'
  get 'feedback/thanks' => 'feedback#thanks', :as => 'thanks_feedback'
  post 'feedback' => 'feedback#create', :as => 'feedback'

  resources :departments, :only => [:index, :show] do
    get 'info', :action => :info, :on => :collection, :as => :info
  end

  resources :petitions, :only => [:new, :show, :index] do
    collection do
      get 'check'
      get 'check_results'
    end

    member do
      post 'resend_confirmation_email'
      get  'thank-you', :action => :thank_you, :as => :thank_you
    end

    resource :signature, :only => [:new] do
      post 'new' => 'signatures#create', :as => :sign
      get 'thank-you', :action => :thank_you, :on => :collection, :as => :thank_you
      get 'signed', :action => :signed, :on => :collection, :as => :signed
    end
  end

  post 'petitions/new' => 'petitions#create', :as => :create_petition

  get 'search' => 'search#search', :as => :search

  resources :signatures, :only => [] do
    get 'verify/:token', :action => :verify, :on => :member, :as => :verify
  end

  namespace :admin do
    root :to => 'todolist#index'

    resource :search, :only => [:new] do
      get :result, :on => :member
      get :petition_by_id, :on => :member
    end

    resources :admin_users
    resources :petitions, :only => [:show, :edit, :update, :index] do
      collection do
        get :threshold
      end
      member do
        get :edit_response
        put :update_response
        get :edit_internal_response
        put :update_internal_response
        put :take_down
      end
    end
    resources :profile, :only => [:edit, :update]
    resources :reports,  :only => [:index]
    resources :user_sessions, :only => [:create]
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'login' => 'user_sessions#new', :as => :login
  end

  namespace :api do
    resources :petitions, :only => [:index, :show]
  end
end

app/models/petition.rb
# == Schema Information
#
# Table name: petitions
#
#  id                   :integer(4)      not null, primary key
#  title                :string(255)     not null
#  description          :text
#  response             :text
#  state                :string(10)      default("pending"), not null
#  open_at              :datetime
#  department_id        :integer(4)      not null
#  creator_signature_id :integer(4)      not null
#  created_at           :datetime
#  updated_at           :datetime
#  creator_id           :integer(4)
#  rejection_text       :text
#  closed_at            :datetime
#  signature_count      :integer(4)      default(0)
#  response_required    :boolean(1)      default(FALSE)
#  internal_response    :text
#  rejection_code       :string(50)
#  notified_by_email    :boolean(1)      default(FALSE)
#  duration             :string(2)       default("12")
#  email_requested_at   :datetime
#

class Petition < ActiveRecord::Base
  include State

  attr_accessible :title, :description, :duration, :department_id, :creator_signature_attributes
  after_create :set_petition_on_creator_signature

  searchable do
    text :title
    text :description
    text :creator_name do
      creator_signature.name
    end
    text :department_name do
      department.name
    end
    string :title
    integer :signature_count
    time :closed_at, :trie => true
    time :created_at, :trie => true
    string :state
  end

  # = Relationships =
  belongs_to :department
  belongs_to :creator_signature, :class_name => 'Signature'
  accepts_nested_attributes_for :creator_signature
  has_many :signatures
  has_many :department_assignments

  # = Validations =
  validates_presence_of :response, :if => :email_signees, :message => "must be completed when email signees is checked"
  validates_presence_of :open_at, :closed_at, :if => :open?
  validates_presence_of :rejection_code, :if => :rejected?
  # Note: we only validate creator_signature on create since if we always load creator_signature on validation then
  # when we save a petition, the after_update on the creator_signature gets fired. An overhead that is unecesssary.
  validates_presence_of :creator_signature, :message => "%{attribute} must be completed", :on => :create
  validates_presence_of :title, :description, :duration, :department, :message => "%{attribute} must be completed"
  validates_inclusion_of :state, :in => STATES, :message => "'%{value}' not recognised"
  validates_length_of :title, :maximum => 150, :unless => 'title.blank?', :message => 'Title is too long.'
  validates_length_of :description, :maximum => 1000, :unless => 'description.blank?', :message => 'Description is too long.'

  attr_accessor :email_signees

  # = Finders =
  scope :threshold, lambda {{
        :conditions => ['signature_count >= ? or response_required = ?',
                        SystemSetting.value_of_key(SystemSetting::THRESHOLD_SIGNATURE_COUNT).to_i, true] }}
  scope :for_state, lambda { |state|
    if CLOSED_STATE.casecmp(state) == 0
      {:conditions => ['state = ? and closed_at < ?', OPEN_STATE, Time.zone.now]}
    elsif OPEN_STATE.casecmp(state) == 0
      {:conditions => ['state = ? and closed_at >= ?', OPEN_STATE, Time.zone.now]}
    else
      {:conditions => ['state = ?', state]}
    end
  }
  scope :for_departments, lambda {|departments| {:conditions => ['department_id in (?)', departments.map(&:id)]}}
  scope :visible, :conditions => ['state in (?)', VISIBLE_STATES]
  scope :moderated, :conditions => ['state in (?)', MODERATED_STATES]
  scope :trending, lambda { |number_of_days|
                    joins(:signatures).
                    where("signatures.state" => "validated").
                    where("signatures.updated_at > ?", number_of_days.day.ago).
                    order("count('signatures.id') DESC").
                    group('petitions.id').
                    limit(10)
                  }
  scope :last_hour_trending, joins(:signatures).
                             select("petitions.id as id, count('signatures.id') as signatures_in_last_hour").
                             where("signatures.state" => "validated").
                             where("signatures.updated_at > ?", 1.hour.ago).
                             order("signatures_in_last_hour DESC").
                             group('petitions.id').
                             limit(12)

  def self.update_all_signature_counts
    Petition.visible.each do |petition|
      petition_current_count = petition.count_validated_signatures
      if petition_current_count != petition.signature_count
        petition.update_attribute(:signature_count, petition_current_count)
      end
    end
  end

  def self.counts_by_state
    counts_by_state = {}
    states = State::STATES + [CLOSED_STATE]
    states.each do |key_name|
      counts_by_state[key_name.to_sym] = for_state(key_name.to_s).count
    end
    counts_by_state
  end

  def reassign!(new_department)
    self.department = new_department
    save!
    department_assignments.create!(:department => new_department, :assigned_on => Time.now)
  end

  def count_validated_signatures
    signatures.validated.count
  end

  def need_emailing
    signatures.need_emailing(email_requested_at)
  end

  def awaiting_moderation?
    self.state == VALIDATED_STATE
  end

  def open?
    self.state == OPEN_STATE
  end

  def can_be_signed?
    self.state == OPEN_STATE and self.closed_at > Time.zone.now
  end

  def rejected?
    self.state == REJECTED_STATE
  end

  def hidden?
    self.state == HIDDEN_STATE
  end

  def closed?
    self.state == OPEN_STATE && self.closed_at <= Time.zone.now
  end

  def state_label
    if (self.closed?)
      CLOSED_STATE
    else
      self.state
    end
  end

  def rejection_reason
    RejectionReason.find_by_code(self.rejection_code).title
  end

  def rejection_description
    RejectionReason.find_by_code(self.rejection_code).description
  end

  def editable_by?(user)
    return true if user.is_a_threshold? || user.is_a_sysadmin?
    return true if user.departments.include?(department)
    return false
  end

  def response_editable_by?(user)
    return true if user.is_a_threshold? || user.is_a_sysadmin?
    return false
  end

  # need this callback since the relationship is circular
  def set_petition_on_creator_signature
    self.creator_signature.update_attribute(:petition_id, self.id)
  end

  def signature_counts_by_postal_district
    Hash.new(0).tap do |counts|
      signatures.validated.find_each do |signature|
        counts[signature.postal_district] += 1 if signature.postal_district.present?
      end
    end
  end
end

app/controllers/admin/petitions_controller.rb
class Admin::PetitionsController < Admin::AdminController
  before_filter :assign_departments, :only => [:edit, :update]
  
  respond_to :html

  def index
    if current_user.is_a_sysadmin? or current_user.is_a_threshold?
      @petitions = Petition
    else
      @petitions = Petition.for_departments(current_user.departments)
    end
    @petitions = @petitions.moderated.order(:signature_count)
    @petitions = @petitions.for_state(params[:state]) unless params[:state].blank?
    @petitions = @petitions.paginate(:page => params[:page], :per_page => params[:per_page] || 20)
  end

  def show
    @petition = Petition.find(params[:id])
  end
  
  def edit
    @petition = Petition.for_state(Petition::VALIDATED_STATE).find(params[:id])
  end
  
  def update
    @petition = Petition.for_state(Petition::VALIDATED_STATE).find(params[:id])
    user_action = params['commit']
    case user_action
      when 'Publish this petition'
        publish
      when 'Re-assign'
        reassign
      when 'Reject'
        reject
      else
        raise "Don't know how to do this action"
    end

    respond_with @petition, :location => admin_root_path
  end
  
  def threshold
    @petitions = Petition.threshold.order(:signature_count).paginate(:page => params[:page], :per_page => params[:per_page] || 20)
  end
  
  def edit_response
    @petition = Petition.find(params[:id])
  end
  
  def update_response
    @petition = Petition.find(params[:id])
    @petition.internal_response = params[:petition][:internal_response]
    @petition.response_required = params[:petition][:response_required]
    @petition.response = params[:petition][:response]
    @petition.email_signees = params[:petition][:email_signees] == '1'
    if @petition.save
      # if email signees has been selected then set up a delayed job to email out to all signees who opted in
      if @petition.email_signees
        # run the job at some random point beween midnight and 4 am
        requested_at = Time.zone.now
        @petition.update_attribute(:email_requested_at, requested_at)
        Delayed::Job.enqueue EmailThresholdResponseJob.new(@petition.id, requested_at, Petition, PetitionMailer), :run_at => 1.day.from_now.at_midnight + rand(240).minutes + rand(60).seconds
      end
      
      redirect_to threshold_admin_petitions_path
    else
      render :edit_response
    end
  end

  def take_down
    @petition = Petition.find(params[:id])
    reject
    respond_with @petition, :location => admin_petitions_path
  end
  
  def edit_internal_response
    @petition = Petition.find(params[:id])
  end
  
  def update_internal_response
    @petition = Petition.find(params[:id])
    @petition.internal_response = params[:petition][:internal_response]
    @petition.response_required = params[:petition][:response_required]
    @petition.save!
    redirect_to admin_petitions_path
  end
  
  protected
  
  def publish
    @petition.state = Petition::OPEN_STATE
    @petition.open_at = Time.zone.now
    @petition.closed_at = @petition.duration.to_i.months.from_now
    @petition.save!
    PetitionMailer.notify_creator_that_petition_is_published(@petition.creator_signature).deliver
  end

  def reassign
    department = Department.find(params[:petition][:department_id])
    @petition.reassign!(department)
  end

  def reject
    @petition.rejection_code = params[:petition][:rejection_code]
    @petition.rejection_text = params[:petition][:rejection_text]

    # if a petition is rejected for a reason that means it should be hidden, then set the state accordingly
    reason = RejectionReason.find_by_code(@petition.rejection_code)
    if reason and ! reason.published
      @petition.state = Petition::HIDDEN_STATE
    else
      @petition.state = Petition::REJECTED_STATE
    end
    
    # send rejection email 
    if @petition.save
      PetitionMailer.notify_creator_that_petition_is_rejected(@petition.creator_signature).deliver
    end
  end
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_filter :assign_departments, :only => [:new, :create]
  before_filter :sanitise_page_param
  caches_action_with_params :index

  caches_page :show

  ssl_required :new, :create
  ssl_allowed :thank_you

  respond_to :html

  include SearchResultsSetup

  def index
    results_for(Petition)
  end

  def new
    @petition = Petition.new(:title => params[:title])
    @petition.build_creator_signature(:country => 'United Kingdom')
    @start_on_section = 0;
    respond_with @petition
  end

  def show
    respond_with @petition = Petition.visible.find(params[:id])
  end

  def create
    params[:petition][:creator_signature_attributes][:humanity] = Captcha.verify(params[:captcha_response_field], params[:captcha_string])

    @petition = Petition.new(params[:petition])
    @petition.creator_signature.email.strip!
    if @petition.creator_signature
      @petition.creator_signature.ip_address = request.remote_ip
      @petition.creator_signature.notify_by_email = true
    end

    @petition.title.strip!
    if @petition.save
      send_email_to_verify_petition_creator(@petition)
      redirect_to thank_you_petition_path(@petition, :secure => true)
    else
      if @petition.errors[:title].any? ||
        @petition.errors[:department].any? ||
        @petition.errors[:description].any?
        @start_on_section = 0
      elsif @petition.creator_signature.errors[:name].any? ||
        @petition.creator_signature.errors[:email].any? ||
        @petition.creator_signature.errors[:uk_citizenship].any? ||
        @petition.creator_signature.errors[:address].any? ||
        @petition.creator_signature.errors[:town].any? ||
        @petition.creator_signature.errors[:postcode].any? ||
        @petition.creator_signature.errors[:country].any?
        @start_on_section = 1
      elsif @petition.creator_signature.errors[:humanity].any?
        @start_on_section = 2
      else
        @start_on_section = 0
      end
      render :new
    end
  end

  def check
  end

  def check_results
    @petition_search = PetitionResults.new(
      :search_term    => params[:search],
      :state => params[:state],
      :per_page       => 10,
      :page_number    => params[:page],
      :sort           => params[:sort],
      :order          => params[:order]
    )
  end

  def resend_confirmation_email
    @petition = Petition.visible.find(params[:id])
    SignatureConfirmer.new(@petition, params[:confirmation_email], PetitionMailer, Authlogic::Regex.email).confirm!
  end

  protected

  def send_email_to_verify_petition_creator(petition)
    PetitionMailer.email_confirmation_for_creator(petition.creator_signature).deliver
  end
end

app/views/admin/petitions/_internal_response.html.erb
<div>
  <%= f.text_area :internal_response, :rows => 8, :cols => 70 %>
  <%= f.check_box :response_required, :label => 'Public response required', :class => 'checkbox' %>
</div>

app/views/admin/petitions/_petition.html.erb
<tr>
  <td class='petition_id'><%= petition.id %></td>
  <td><%= link_to petition.title, edit_response_admin_petition_path(petition) %></td>
  <td>
    <%= petition.creator_signature.name %><br/>
    <%= mail_to petition.creator_signature.email %>
  </td>
  <td class="count"><%= number_with_delimiter(petition.signature_count) %></td>
  <td><%= date_format_admin(petition.closed_at) %></td>
  <td class="center"><%= petition.response.present? ? image_tag('admin/tick.gif') : '' %></td>
</tr>

app/views/admin/petitions/_petition_details.html.erb
<div class="row">
  <label>Petition Id:</label>
  <p class="text_block"><%=  @petition.id %></p>
</div>

<div class="row">
  <label>Petition title:</label>
  <p class="text_block"><%=  @petition.title %></p>
</div>

<div class="row">
  <label>Creator:</label><%=  @petition.creator_signature.name %> - <%= @petition.creator_signature.email %>
</div>

<div class="row">
  <label>Created date:</label><%= date_time_format(@petition.created_at) %>
</div>

<div class="row">
  <label>Department:</label>
  <% if params[:action] == 'edit' or params[:action] == 'update' -%>
    <%= f.select :department_id, options_from_collection_for_select(@departments, :id, :name, @petition.department_id.to_s) %>
    <%= submit_tag 'Re-assign' %>
  <% else -%>
    <%= @petition.department.name %>
  <% end -%>
</div>

<div class="row">
  <label>Petition description:</label>
  <p class="text_block"><%= raw auto_link(h(@petition.description), :html => { :target => '_blank' }) %></p>
</div>

app/views/admin/petitions/_published_petition_details.html.erb
<div class="row">
  <label>Open:</label>
  <p class="text_block"><%= date_format_admin(@petition.open_at) %>&nbsp;</p>
</div>

<div class="row">
  <label>Closing:</label>
  <p class="text_block"><%= date_format_admin(@petition.closed_at) %>&nbsp;</p>
</div>

<div class="row">
  <label>Signature count:</label>
  <p class="text_block"><%= number_with_delimiter(@petition.signature_count) %>&nbsp;</p>
</div>

<div class="row">
  <label>State:</label>
  <p class="text_block"><%= @petition.state_label %>&nbsp;</p>
</div>

<% if @petition.rejected? or @petition.hidden? -%>
  <div class="row">
    <label>Rejection reason:</label>
    <p class="text_block"><%= @petition.rejection_reason %>&nbsp;</p>
  </div>

  <div class="row">
    <label>Rejection text:</label>
    <p class="text_block"><%= @petition.rejection_text %>&nbsp;</p>
  </div>
<% end -%>

app/views/admin/petitions/_reject.html.erb
<div>
  <%= javascript_tag do %>
    var rejection_reasons = <%= IO.read(RejectionReason::FILE).html_safe %>;

    $().ready(function() {
      // Ensure that we get the onchange event when the users uses the keyboard
      // Details: http://bit.ly/iZx9nh
      $('#petition_rejection_code').keyup(function() {
        this.blur();
        this.focus();
      });

      $('#petition_rejection_code').change(function() {
        $('#rejection_preview').show();
        $('#rejection_preview .content').html(rejection_reasons[$(this).val()].description);
      });
    });
  <% end -%>
  <%= f.label :rejection_code, 'Rejection reason' %><br />
  <%= f.select :rejection_code, RejectionReason.options_for_select, {:include_blank => "-- Select a rejection code --" } %>
  <%= error_messages_for_field @petition, :rejection_code %>
  <div id='rejection_preview' class='flash_notice' style='display:none'>
    <h3>Preview of the standard text that will be sent to the petition creator:</h3>
    <div class='content'></div>
  </div>
  <%= f.text_area :rejection_text, :rows => 8, :cols => 70 %>
  <%= submit_tag button_label || 'Reject' %>
</div>

app/views/admin/petitions/edit.html.erb
<%= form_for [:admin, @petition ], :builder => AdminFormBuilder do |f| -%>

  <%= render :partial => 'petition_details', :locals => { :f => f } %>

  <div class="row">
    <label>Duration:</label>
    <p class="text_block"><%= @petition.duration %> months</p>
  </div>

  <div>
    <%= submit_tag 'Publish this petition', :confirm => "Are you sure you want to publish this petition?" %>
  </div>

  <%= render :partial => 'reject', :locals => { :f => f, :button_label => "Reject" } %>
<% end -%>

<br />

<h2>Department Assignment History</h2>

<% if @petition.department_assignments.present? %>
  <table class="admin_index">
    <tr>
      <th>Department</th>
      <th>Assigned On</th>
    </tr>

    <% @petition.department_assignments.each do |department_assignment| %>
      <tr>
        <td><%= department_assignment.department.name %></td>
        <td><%= date_time_format department_assignment.assigned_on %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>No department assignment history</p>
<% end %>

app/views/admin/petitions/edit_internal_response.html.erb
<%= form_for [:admin, @petition ], :url => update_internal_response_admin_petition_path(@petition), :builder => AdminFormBuilder do |f| -%>
  
  <%= render 'petition_details', :f => f %>
  <%= render 'published_petition_details', :f => f %>
  <%= render 'internal_response', :f => f %>

  <div>
    <%= submit_tag 'Save' %>
  </div>

<% end -%>
<% if current_user.can_take_petitions_down? && @petition.can_be_signed? %>
  <%= form_for [:admin, @petition ], :url => take_down_admin_petition_path(@petition), :builder => AdminFormBuilder do |f| -%>
    <div class='takedown'>
      <h2>Take this petition down</h2>
      <%= render :partial => 'reject', :locals => { :f => f, :button_label => "Take down" } %>
    </div>
  <% end -%>
<% elsif @petition.rejected? -%>
  <%= form_for [:admin, @petition ], :url => take_down_admin_petition_path(@petition), :builder => AdminFormBuilder do |f| -%>
    <div class='takedown'>
      <h2>Change rejection status</h2>
      <p>Changing the rejected state of this petition will affect if it can be seen on the website or not.</p>
      <%= render :partial => 'reject', :locals => { :f => f, :button_label => "Change rejection status" } %>
    </div>
  <% end -%>
<% end -%>

app/views/admin/petitions/edit_response.html.erb
<%= form_for [:admin, @petition ], :url => update_response_admin_petition_path(@petition), :builder => AdminFormBuilder do |f| -%>
  
  <%= render 'petition_details', :f => f %>
  <%= render 'published_petition_details' %>
  <%= render 'internal_response', :f => f %>
  
  <div>
    <%= f.text_area :response, :label => 'Public response', :rows => 8, :cols => 70 %>
    <%= error_messages_for_field @petition, :response %>
  
    <%= f.check_box :email_signees, :class => 'checkbox' %>

    <%= submit_tag 'Save' %>
  </div>
<% end -%>
<% content_for :js do -%>
<script type="text/javascript">
//<![CDATA[
$().ready(function() {
  new EditResponseController({form:'form.edit_petition', confirm_if_checked: '#petition_email_signees', message: "This action will send an email to each person who signed this petition. Are you sure you want to do this?"});
});
//]]>
</script>
<% end -%>

app/views/admin/petitions/index.html.erb
<%= form_tag admin_petitions_path, :method => :get, :class => "filter" do -%>
  <%= label_tag :state, "Filter by status:" %>
  <%= select_tag :state, options_for_select(Petition::SELECTABLE_STATES, params[:state]), :include_blank => "-- all moderated petitions --" %>
  <%= label_tag :per_page, "Results per page:" %>
  <%= select_tag :per_page, options_for_select(%w(20 50 100), params[:per_page]) %>
  <%= submit_tag "Go" %>
<% end -%>
<table class="admin_index">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Creator</th>
      <th>State</th>
      <th>Count</th>
      <th>Closing date</th>
    </tr>
  </thead>
  <tbody>
    <% @petitions.each do |petition| -%>
      <tr>
        <td class='petition_id'><%= petition.id %></td>
        <td><%= link_to petition.title, edit_internal_response_admin_petition_path(petition) %></td>
        <td><%= petition.creator_signature.name %><br/>
        <%= mail_to petition.creator_signature.email %></td>
        <td><%= petition.state_label %></td>
        <td class="count"><%= number_with_delimiter(petition.signature_count) %></td>
        <td><%= date_format_admin(petition.closed_at) %></td>
      </tr>
    <% end -%>
  </tbody>

  <%= will_paginate(@petitions) if @petitions.any? %>
</table>

app/views/admin/petitions/show.html.erb
<div class='petition'>
  <%= render 'petition_details' %>
  <%= render 'published_petition_details' %>
  <div class="row">
    <label>Public Response:</label>
    <p class="text_block"><%= @petition.response %></p>
  </div>
</div>

app/views/admin/petitions/threshold.html.erb
<%= render 'admin/shared/results_per_page', :path => threshold_admin_petitions_path %>
<table class="admin_index">
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Creator</th>
    <th>Count</th>
    <th>Closing date</th>
    <th>Response</th>
  </tr>
  <%= render @petitions -%>
  <%= will_paginate(@petitions) if @petitions.any? %>
</table>