config/routes.rb
Epets::Application.routes.draw do
  match '/' => 'static_pages#home', :as => :home
  match 'accessibility' => 'static_pages#accessibility', :as => 'accessibility'
  match 'how-it-works' => 'static_pages#how_it_works', :as => 'how_it_works'
  match 'terms-and-conditions' => 'static_pages#terms_and_conditions', :as => 'terms_and_conditions'
  match 'privacy-policy' => 'static_pages#privacy_policy', :as => 'privacy_policy'
  match 'crown-copyright' => 'static_pages#crown_copyright', :as => 'crown_copyright'
  match 'faq' => 'static_pages#faq', :as => 'faq'

  get 'feedback' => 'feedback#index', :as => 'feedback'
  get 'feedback/thanks' => 'feedback#thanks', :as => 'thanks_feedback'
  post 'feedback' => 'feedback#create', :as => 'feedback'

  resources :departments, :only => [:index, :show] do
    get 'info', :action => :info, :on => :collection, :as => :info
  end

  resources :petitions, :only => [:new, :show, :index] do
    collection do
      get 'check'
      get 'check_results'
    end

    member do
      post 'resend_confirmation_email'
      get  'thank-you', :action => :thank_you, :as => :thank_you
    end

    resource :signature, :only => [:new] do
      post 'new' => 'signatures#create', :as => :sign
      get 'thank-you', :action => :thank_you, :on => :collection, :as => :thank_you
      get 'signed', :action => :signed, :on => :collection, :as => :signed
    end
  end

  post 'petitions/new' => 'petitions#create', :as => :create_petition

  get 'search' => 'search#search', :as => :search

  resources :signatures, :only => [] do
    get 'verify/:token', :action => :verify, :on => :member, :as => :verify
  end

  namespace :admin do
    root :to => 'todolist#index'

    resource :search, :only => [:new] do
      get :result, :on => :member
      get :petition_by_id, :on => :member
    end

    resources :admin_users
    resources :petitions, :only => [:show, :edit, :update, :index] do
      collection do
        get :threshold
      end
      member do
        get :edit_response
        put :update_response
        get :edit_internal_response
        put :update_internal_response
        put :take_down
      end
    end
    resources :profile, :only => [:edit, :update]
    resources :reports,  :only => [:index]
    resources :user_sessions, :only => [:create]
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'login' => 'user_sessions#new', :as => :login
  end

  namespace :api do
    resources :petitions, :only => [:index, :show]
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController

  def index
    @counts = Petition.counts_by_state
    @departments = Department.by_petition_count

    departments_for_trending = current_user.can_see_all_trending_petitions? ? Department.all : current_user.departments
    @number_of_days_to_trend  = params[:number_of_days_to_trend].present? ? params[:number_of_days_to_trend].to_i : 1
    @trending_petitions = Petition.for_departments(departments_for_trending).trending(@number_of_days_to_trend)
  end

end

app/views/admin/reports/index.html.erb
<h1>e-petition statistics</h1>
<br />
<h2>Trending Petitions</h2>

<%= form_tag admin_reports_path, :method => :get, :class => "filter" do -%>
  <%= label_tag :number_of_days_to_trend, "View trends for:" %>
  <%= select_tag :number_of_days_to_trend,
    options_for_select([['24 hours', 1], ['7 days', 7]], @number_of_days_to_trend), :include_blank => false %>
  <%= submit_tag "Go" %>
<% end -%>

<% if @trending_petitions.present? %>
  <table class="trending_petitions">
    <thead>
      <tr>
        <th>Petition ID</th>
        <th>Title</th>
        <th>Signatures in last <%= @number_of_days_to_trend == 1 ? "24 hours" : "7 days" %></th>
      </tr>
    </thead>
    <tbody>
      <% @trending_petitions.each do |petition| %>
        <tr class="trending_petition">
          <td><%= petition.id %></td>
          <td class="title"><%= link_to petition.title, [:edit_internal_response, :admin, petition] %></td>
          <td class="count"><%= petition.signatures.in_days(@number_of_days_to_trend).count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No petitions in the chosen period.</p>
  <br />
<% end %>


<div id="num_petitions_per_department_report">
  <h2>Number of petitions per department</h2>

  <table class="admin_report">
    <tr>
      <th></th>
      <th>Pending</th>
      <th>Validated</th>
      <th>Open</th>
      <th>Closed</th>
      <th>Rejected</th>
      <th>Total</th>
    </tr>

    <tr class="heavy_bottom_border">
      <td>All Departments</td>
      <td class="count"><%= number_with_delimiter(@counts[:pending]) %></td>
      <td class="count"><%= number_with_delimiter(@counts[:validated]) %></td>
      <td class="count"><%= number_with_delimiter(@counts[:open]) %></td>
      <td class="count"><%= number_with_delimiter(@counts[:closed]) %></td>
      <td class="count"><%= number_with_delimiter(@counts[:rejected] + @counts[:hidden]) %></td>
      <td class="count"><%= number_with_delimiter(@counts.values.sum) %></td>
    </tr>

    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td class="count"><%= number_with_delimiter(department.petitions.for_state(State::PENDING_STATE).count) %></td>
        <td class="count"><%= number_with_delimiter(department.petitions.for_state(State::VALIDATED_STATE).count) %></td>
        <td class="count"><%= number_with_delimiter(department.petitions.for_state(State::OPEN_STATE).count) %></td>
        <td class="count"><%= number_with_delimiter(department.petitions.for_state(State::CLOSED_STATE).count) %></td>
        <td class="count"><%= number_with_delimiter(department.petitions.for_state(State::REJECTED_STATE).count + department.petitions.for_state(State::HIDDEN_STATE).count) %></td>
        <td class="count"><%= number_with_delimiter(department.petitions.count) %></td>
      </tr>
    <% end %>

  </table>
</div>